import { Language, Translation, Merchant } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.AMHARIC]: {
    title: "ጤፍ ኤክስፖ",
    heroTitle: "ምርጥ የኢትዮጵያ ጤፍ በቀጥታ ከነጋዴዎች",
    heroSub: "ጥራት ያለው ነጭ፣ ቀይ እና ሰርገኛ ጤፍ በፈለጉት መጠን ይዘዙ።",
    merchantLogin: "የነጋዴ መግቢያ",
    merchantRegister: "ነጋዴ ለመሆን ይመዝገቡ",
    browseTeff: "ጤፍ ይግዙ",
    buyNow: "ይግዙ",
    kilo: "ኪሎ",
    pricePerKilo: "የአንድ ኪሎ ዋጋ",
    totalPrice: "ጠቅላላ ዋጋ",
    whiteTeff: "ነጭ ጤፍ",
    redTeff: "ቀይ ጤፍ",
    mixedTeff: "ሰርገኛ ጤፍ",
    paymentInstructions: "ክፍያ በመተግበሪያዎ (Mobile Banking) በቀጥታ ወደ ባንክ ሂሳብ ይላኩ",
    bankAccount: "ባንክ",
    accountNumber: "የሂሳብ ቁጥር",
    stockAvailable: "በክምችት ላይ ያለው",
    noStock: "አልቆብናል",
    quantity: "መጠን",
    placeOrder: "ትዕዛዝ ይላኩ",
    paymentNotice: "ትዕዛዝዎን ካረጋገጡ በኋላ ደረሰኙን ለነጋዴው ያሳውቁ።",
    merchantDashboard: "የነጋዴ ዳሽቦርድ",
    updateStock: "ክምችት ያድሱ",
    logout: "ውጣ",
    aiAssistant: "የጤፍ ረዳት",
    aiPlaceholder: "ስለ ጤፍ ጥራት ወይም አይነት ይጠይቁ...",
    cart: "ካርት",
    checkout: "ጨርስ",
    continueShopping: "መግዛት ይቀጥሉ",
    cartEmpty: "ካርትዎ ባዶ ነው",
    addToCart: "ወደ ካርት ያክሉ",
    remove: "አስወግድ",
    proceedToCheckout: "ወደ ጨርስ ይሂዱ",
    customerInformation: "የደንበኛ መረጃ",
    name: "ስም",
    phone: "ስልክ",
    email: "ኢሜይል",
    address: "አድራሻ",
    kebele: "ቀበሌ",
    googleMapsLink: "የጉግል ካርታ አድራሻ",
    paymentProof: "የክፍያ ማስረጃ",
    required: "ግዴታ",
    optional: "አማራጭ",
    placingOrder: "ትዕዛዝ በመላክ ላይ...",
    orderSummary: "የትዕዛዝ ማጠቃለያ",
    orderPlaced: "ትዕዛዝዎ ተልኳል!",
    adminDashboard: "የአስተዳዳሪ ዳሽቦርድ",
    allOrders: "ሁሉም ትዕዛዞች",
    merchantBreakdown: "የነጋዴ መበስበስ",
    assignToMerchants: "ለነጋዴዎች አድርግ",
    markAsCompleted: "እንደተጠናቀቀ ምልክት አድርግ",
    notificationMethod: "የማሳወቂያ ዘዴ",
    dashboardMessage: "የዳሽቦርድ መልዕክት",
    phoneCall: "የስልክ ጥሪ",
    both: "ሁለቱም",
    selectMerchants: "ነጋዴዎችን ይምረጡ",
    cancel: "ይቅር",
    assign: "አድርግ",
    orders: "ትዕዛዞች",
    products: "ምርቶች",
    notifications: "ማሳወቂያዎች",
    new: "አዲስ",
    noOrders: "ትዕዛዝ የለም",
    noNotifications: "ማሳወቂያ የለም",
    markAllAsRead: "ሁሉንም እንደተነበበ ምልክት አድርግ",
    confirmOrder: "ትዕዛዝ ያረጋግጡ",
    confirm: "አረጋግጥ",
    customer: "ደንበኛ",
    status: "ሁኔታ",
    amount: "መጠን",
    items: "ንጥሎች",
    pending: "በመጠባበቅ ላይ",
    assigned: "ተመድቧል",
    completed: "ተጠናቋል",
    confirmed: "ተጠናቋል",
    myAmount: "የእኔ መጠን",
    myItems: "የእኔ ንጥሎች",
    myProducts: "የእኔ ምርቶች",
    stock: "ክምችት",
    price: "ዋጋ",
    viewOnMap: "በካርታው ላይ ይመልከቱ",
    subtotal: "ከታክስ በፊት ዋጋ",
    addMerchant: "ነጋዴ ጨምር",
    deleteMerchant: "ነጋዴ ሰርዝ",
    editMerchant: "ነጋዴ ያርሙ",
    merchants: "ነጋዴዎች",
    password: "የይለፍ ቃል",
    storeLocation: "የመደብር አድራሻ (Google Maps)",
    photoUrl: "የፎቶ አድራሻ",
    delivery: "ማድረሻ",
    vatIncluded: "ተጨማሪ እሴት ታክስ (VAT) ጨምሮ",
    fastDelivery: "ፈጣን የቤት ለቤት ማድረሻ",
    secureTransaction: "አስተማማኝ ክፍያ",
    minOrder: "ቢያንስ 0.5 ኪሎ",
    refreshData: "ዳታ አድስ",
    lastSynced: "ለመጨረሻ ጊዜ የታደሰው",
    searchItems: "ፈልግ...",
    calculatedAtNextStep: "በሚቀጥለው ደረጃ የሚሰላ",
    syncingCart: "ካርቱን በማመሳሰል ላይ...",
    cartDescription: "ምርጥ ጥራት ያለው ጤፍ ወደ ካርትዎ እስካሁን አልጨመሩም። ምርጫዎቻችንን ይመልከቱ እና ለቤትዎ የሚስማማውን ይምረጡ።",
    secureNotice: "በባንክ ዝውውር በጤፍ ኤክስፖ የተረጋገጠ",
    addisDeliveryTime: "ከ2-4 ሰዓት ውስጥ አዲስ አበባ",
    activeOrders: "ንቁ ትዕዛዞች",
    totalRevenue: "ጠቅላላ ገቢ",
    unreadAlerts: "ያልተነበቡ ማንቂያዎች",
    teffTypes: "የጤፍ አይነቶች",
    inventory: "ክምችት",
    addGrains: "ጤፍ ጨምር",
    callCustomer: "ለደንበኛው ይደውሉ",
    welcomeBack: "እንኳን ደህና መጡ",
    noOrdersDescription: "አዲስ የደንበኞች ትዕዛዝ ሲመጣ እዚህ ይታያሉ።",
    noNotificationsDescription: "ምንም አዲስ ማሳወቂያ የለም።",
    commitToInventory: "ወደ ክምችት ጨምር",
    teffTypeSelection: "የጤፍ አይነት ይምረጡ",
    pricePerKiloLabel: "የአንድ ኪሎ ዋጋ (ብር)",
    availableStockLabel: "በክምችት ላይ ያለ (ኪሎ)",
    detailedDescription: "ዝርዝር መግለጫ",
    descriptionPlaceholder: "ስለ ጥራቱ፣ ስለ አመራረቱ እና ስለ መነሻው ይግለጹ...",
    exploreMarket: "የእኛን የገበያ ቦታ ያስሱ",
    allTypes: "ሁሉም ዓይነቶች",
    verifiedMerchant: "የተረጋገጠ ነጋዴ",
    availableWeight: "የሚገኝ ክብደት",
    perKilo: "/ ኪሎ",
    popularTeff: "ታዋቂ ጤፍ",
    fastDeliveryTitle: "በጣም ፈጣን ማድረስ",
    trustedMerchantsTitle: "ታማኝ የአካባቢ ነጋዴዎች",
    qualityGuaranteedTitle: "ጥራት የተረጋገጠ",
    howItWorks: "እንዴት እንደሚሰራ",
    step1Title: "ጤፍዎን ይምረጡ",
    step2Title: "አስተማማኝ ክፍያ",
    step3Title: "ቀጥታ ማድረስ",
    footerAbout: "የኢትዮጵያን ባህል ከዘመናዊው ዲጂታል ዓለም ጋር ማገናኘት። ከፍተኛ ጥራት ያለው ጤፍ፣ በቀጥታ በመገኘት፣ በጥንቃቄ ቀርቧል።",
    legal: "ህጋዊ",
    termsOfService: "የአገልግሎት ውሎች",
    privacyPolicy: "የግላዊነት ፖሊሲ",
    potentialEarnings: "ሊገኝ የሚችል ገቢ",
    confirmedEarnings: "የተረጋገጠ ገቢ",
    moneyGained: "ያገኙት ገንዘብ",
    orderConfirmed: "ትዕዛዙ ተረጋግጧል",
    ready: "ዝግጁ",
    readyForDelivery: "ለማድረስ ዝግጁ",
    notifyAdmin: "ለአስተዳዳሪው ያሳውቁ"
  },
  [Language.ENGLISH]: {
    title: "TeffExpo",
    heroTitle: "Premium Ethiopian Teff Direct from Merchants",
    heroSub: "Order quality White, Red, and Mixed Teff in any quantity.",
    merchantLogin: "Merchant Login",
    merchantRegister: "Register as Merchant",
    browseTeff: "Browse Teff",
    buyNow: "Buy Now",
    kilo: "kg",
    pricePerKilo: "Price per kg",
    totalPrice: "Total Price",
    whiteTeff: "White Teff",
    redTeff: "Red Teff",
    mixedTeff: "Mixed Teff",
    paymentInstructions: "Send payment via Mobile Banking directly to the bank account",
    bankAccount: "Bank",
    accountNumber: "Account Number",
    stockAvailable: "In Stock",
    noStock: "Out of Stock",
    quantity: "Quantity",
    placeOrder: "Place Order",
    paymentNotice: "After payment, please notify the merchant with your receipt.",
    merchantDashboard: "Merchant Dashboard",
    updateStock: "Update Stock",
    logout: "Logout",
    aiAssistant: "Teff Assistant",
    aiPlaceholder: "Ask about Teff quality or types...",
    cart: "Cart",
    checkout: "Checkout",
    continueShopping: "Continue Shopping",
    cartEmpty: "Your cart is empty",
    addToCart: "Add to Cart",
    remove: "Remove",
    proceedToCheckout: "Proceed to Checkout",
    customerInformation: "Customer Information",
    name: "Name",
    phone: "Phone",
    email: "Email",
    address: "Address",
    kebele: "Kebele",
    googleMapsLink: "Google Maps Link",
    paymentProof: "Payment Proof",
    required: "Required",
    optional: "Optional",
    placingOrder: "Placing Order...",
    orderSummary: "Order Summary",
    orderPlaced: "Order placed successfully!",
    adminDashboard: "Admin Dashboard",
    allOrders: "All Orders",
    merchantBreakdown: "Merchant Breakdown",
    assignToMerchants: "Assign to Merchants",
    markAsCompleted: "Mark as Completed",
    notificationMethod: "Notification Method",
    dashboardMessage: "Dashboard Message",
    phoneCall: "Phone Call",
    both: "Both",
    selectMerchants: "Select Merchants",
    cancel: "Cancel",
    assign: "Assign",
    orders: "Orders",
    products: "Products",
    notifications: "Notifications",
    new: "New",
    noOrders: "No orders found",
    noNotifications: "No notifications",
    markAllAsRead: "Mark all as read",
    confirmOrder: "Confirm Order",
    confirm: "Confirm",
    customer: "Customer",
    status: "Status",
    amount: "Amount",
    items: "Items",
    pending: "Pending",
    assigned: "Assigned",
    completed: "Completed",
    confirmed: "Confirmed",
    myAmount: "My Amount",
    myItems: "My Items",
    myProducts: "My Products",
    stock: "Stock",
    price: "Price",
    viewOnMap: "View on Map",
    subtotal: "Subtotal",
    addMerchant: "Add Merchant",
    deleteMerchant: "Delete Merchant",
    editMerchant: "Edit Merchant",
    merchants: "Merchants",
    password: "Password",
    storeLocation: "Store Location (Google Maps)",
    photoUrl: "Photo URL",
    delivery: "Delivery",
    vatIncluded: "VAT Included",
    fastDelivery: "Fast Local Delivery",
    secureTransaction: "Secure Transaction",
    minOrder: "Minimum order 0.5 kg",
    refreshData: "Refresh Data",
    lastSynced: "Last Synced",
    searchItems: "Search items...",
    calculatedAtNextStep: "Calculated at next step",
    syncingCart: "Syncing your cart...",
    cartDescription: "Looks like you haven't added any quality Teff to your cart yet. Browse our selection and find the best grain for your table.",
    secureNotice: "Bank transfer verified by TeffExpo",
    addisDeliveryTime: "Within 2-4 hours across Addis",
    activeOrders: "Active Orders",
    totalRevenue: "Total Revenue",
    unreadAlerts: "Unread Alerts",
    teffTypes: "Teff Types",
    inventory: "Inventory",
    addGrains: "Add Grain",
    callCustomer: "Call Customer",
    welcomeBack: "Welcome back",
    noOrdersDescription: "New customer orders will appear here.",
    noNotificationsDescription: "Clear as a summer sky.",
    commitToInventory: "Commit to Inventory",
    teffTypeSelection: "Teff Type Selection",
    pricePerKiloLabel: "Price / Kilo (ETB)",
    availableStockLabel: "Available Stock (Kg)",
    detailedDescription: "Detailed Description",
    descriptionPlaceholder: "Describe the quality, cleaning process, and origin...",
    exploreMarket: "Explore our Marketplace",
    allTypes: "All Types",
    verifiedMerchant: "Verified Merchant",
    availableWeight: "Available weight",
    perKilo: "/ kg",
    popularTeff: "Popular Teff grain",
    fastDeliveryTitle: "Lightning Fast Delivery",
    trustedMerchantsTitle: "Trusted Local Merchants",
    qualityGuaranteedTitle: "Quality Guaranteed",
    howItWorks: "How It Works",
    step1Title: "Select your grain",
    step2Title: "Secure Payment",
    step3Title: "Direct Delivery",
    footerAbout: "Connecting Ethiopia's tradition to the modern digital world. Highest quality teff grain, sourced directly, delivered with care.",
    legal: "Legal",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    potentialEarnings: "Potential Earnings",
    confirmedEarnings: "Confirmed Earnings",
    moneyGained: "Money Gained",
    orderConfirmed: "Order confirmed successfully",
    ready: "Ready",
    readyForDelivery: "Ready for Delivery",
    notifyAdmin: "Notify Admin"
  }
};

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: '1',
    name: "Abebe Teff Store",
    location: "Addis Ababa, Merkato",
    phone: "0911223344",
    bankAccounts: [
      { bankName: "CBE", accountNumber: "1000123456789", holderName: "Abebe Kebede" },
      { bankName: "Abyssinia", accountNumber: "987654321", holderName: "Abebe Kebede" }
    ],
    stock: {
      White: 500,
      Red: 300,
      Mixed: 200
    },
    prices: {
      White: 125,
      Red: 100,
      Mixed: 110
    }
  },
  {
    id: '2',
    name: "Mulugeta Grain Trading",
    location: "Bishoftu",
    phone: "0922334455",
    bankAccounts: [
      { bankName: "CBE", accountNumber: "100099998888", holderName: "Mulugeta Hailu" }
    ],
    stock: {
      White: 1000,
      Red: 500,
      Mixed: 400
    },
    prices: {
      White: 120,
      Red: 95,
      Mixed: 105
    }
  }
];
